### ISSUE TITLE
Adaptar o projeto para o novo formato de dados da Receita Federal

### ISSUE THREAD

**Issue by cuducos** [cuducos/minha-receita#37]
> A RFB informa aos usuários das informações disponibilizadas sobre os dados cadastrais do CNPJ - DADOS ABERTOS, que a partir da divulgação do mês de março de 2021, passará a contar as seguintes novidades:
> 1. A atualização será mensal;
> 2. Contará com novo layout;
> 3. …

[Fonte](https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj).

**Etiquetas**

* _Bug_ e _High priority_ pois não conseguiremos importar os dados novos com a mudança de formato
* _Help wanted_ pois é muito trabalho e contribuições são bem vindas seguindo o _roadmap_ a seguir (e _code review_ também é contribuição valiosa)

**Solução proposta**

Ver detalhes da implementação no `CONTRIBUTING.md` do #70

**Roadmap**

Essa refatoração levará muito mais tempo do que eu imaginava, então deixo aqui o planejando e o andamento:

- [x] Automatizar o download dos dados no novo formato<br>#43
- Ler os dados descomprimindo os arquivos no novo formato: dado um CNPJ `11.222.333/0001-81`, a estratégia é criar arquivo como `tmp/11222333/11222333000181.json` e ir _enriquecendo_ esse arquivo com os dados de cada CSV
    - [x] Ler CSVs de estabelecimentos (ex. `K3241.K03200Y0.D10612.ESTABELE.zip`) e criar o `.json` de cada CNPJ<br>#62
      - [x] Ler CSV de CNAEs primárias (ex. `F.K03200$Z.D10612.CNAECSV.zip`) e enriquecer o `company` antes de escrever o JSON<br>#76
      - [x] Ler CSV de CNAEs secundárias (ex. `F.K03200$Z.D10612.CNAECSV.zip`) e enriquecer o `company` antes de escrever o JSON<br>#77
      - [x] Ler CSV de motivo cadastral (ex. `F.K03200$Z.D10612.MOTICSV.zip`) e enriquecer o `company` antes de escrever o JSON<br>#63
      - [x] Ler CSV de municípios (ex. `F.K03200$Z.D10612.MUNICCSV.zip`) e enriquecer o `company` antes de escrever o JSON<br>#66     
      - [x] Ler CSV de países (ex. `F.K03200$Z.D10612.PAISCSV.zip`) e enriquecer o `company` antes de escrever o JSON<br>#67
    - [x] Ler CSVs de empresas (ex. `K3241.K03200Y0.D10612.EMPRECSV.zip`) e enriquecer o `.json` de cada CNPJe Ler CSV de natureza jurídica (ex. `F.K03200$Z.D10612.NATJUCSV.zip`) e enriquecer o `.json` de cada CNPJ<br>#89
    - [x] Ler CSVs de sócios (ex. `K3241.K03200Y1.D10612.SOCIOCSV.zip`) e enriquecer o `.json` de cada CNPJ<br>#80
    - [x] Ler CSV do Simples (ex. `F.K03200$W.SIMPLES.CSV.D10612.zip`) e enriquecer o `.json` de cada CNPJ<br>#83
- [x] Remodelar o banco de dados (apenas uma chave de CNPJ completo, e um campo JSON)<br>#71
    - [x] Refatorar `ImportData` para não depender de arquivo CSV<br>#88
- [x] Revisar documentação<br>#70
- [x] Testar manualmente com dataset completo
- [ ] Atualizar o banco de dados de produção

**PRs auxiliares**

- [x] #50 
- [x] #54 
- [x] #55 
- [x] #56 
- [x] #58
- [x] #60
- [x] #68 
- [x] #90
- [x] #91
- [x] #92
- [x] #95

(Desconsiderem o #40: o desenvolvimento será feito em PRs menores direcionados à [_branch_ `dev`](https://github.com/cuducos/minha-receita/tree/dev).)

**Comment by cuducos** [comment]
Apenas para registro: os dados [estão indisponíveis](https://twitter.com/cuducos/status/1382827707520544770) nesse momento.

**Comment by cuducos** [comment]
Ainda não consigo baixar todos os arquivos. Ultimamente (nos últimos 5 dias) tem falhado apenas um arquivo (não todos, como reportei há 10 dias atrás). Ainda assim, é problema.

Abri um pedido pela LAI no Fala.BR (Protocolo 03005.076937/2021-37) e estou aguardando resposta. Semana que vem, no dia 3 de maio (salvo engano), vence o prazo para eles responderem.

**Comment by rictom** [comment]
Eu também tava com esse problema. A causa é um erro no link para o arquivo na página da receita. Se vc trocar o D10313 por D10410 o link passa a funcionar.

**Comment by isorensen** [comment]
Existe alguma expectativa de quando isto estará pronto, mesmo com as "outras prioridades" de cada um aqui, nas "vidas próprias"? :-) Abraços

**Comment by cuducos** [comment]
Não. Pretendo temrinar nas próximas semanas, antes do Natal. Mas não posso garantir…

O progresso foi bom esses dias, e o próximo PR é:

> Ler CSVs de estabelecimentos (ex. `K3241.K03200Y0.D10612.ESTABELE.zip`) e criar o `.json` de cada CNPJ

Depois desse PR sei que vai ficar mais fácil receber contribuições, pois a arquitetura de criação dos arquivos estará feira. E tem algumas pessoas que já me procuraram querendo contribuir — então acho que as expectativas são boas de essa meta ser real : )

**Comment by cuducos** [comment]
Aliás, esse próximo PR está num estado bem avançado em uma _branch_ local aqui, só estou com um problema de concorrência que devo resolver na próxima oportunidade que me dedicar ao projeto!

**Comment by cuducos** [comment]
Sobre o que comentei ontem com o @isorensen: estou quase abrindo o PR que cria um JSON por aquivo CNPJ, mas estou patinando em um bug que não consigo identificar.  Subi [a branch](https://github.com/cuducos/minha-receita/tree/task) mas não abri PR ainda pois preciso resulver isso.

No commit da64f2972b3505be8da30111f64adb56a36a0d46, o principal é o `transform/task.go` — teoricamente ele abre todos os CSVs de um “grupo” de CSVs (o de estabelecimentos, no caso) e cria um JSON por CNPJ. Inspecionei com meus métodos rudimentares de debug (`fmt.Println` cof cof) e até a parte do `task.fromRows` funciona legal: o programa [envia linhas do CSV para o canal `task.queue`](https://github.com/cuducos/minha-receita/commit/da64f2972b3505be8da30111f64adb56a36a0d46#diff-5ed85b1139a1b1ae102ac91fc77912af95570f8e42f29ea07785393298656384R52) com sucesso.

Mas o for `r := range t.queue { t.consumeRow(r) }` ali [no `task.consumeRows`](https://github.com/cuducos/minha-receita/commit/da64f2972b3505be8da30111f64adb56a36a0d46#diff-5ed85b1139a1b1ae102ac91fc77912af95570f8e42f29ea07785393298656384R56-R60) nunca lê nenhuma linha e eu ainda não entendi o porquê… o programa fica inativo, mas não se encerra, ou seja… acho que está esperando algo que não está chegando ¯\_(ツ)_/¯ 

Existe um teste para isso, podemos rodar com `go test transform/*` — ele fica inativo (não encerra, nem dá erro).

**Comment by cuducos** [comment]
A princípio, todos os passos completos.

Não consegui fazer um teste total (e, consequentemente) atualizar o banco de dados de produção ainda pois preciso de mais espaço em disco para rodar com os dados completos.

Já esotu vendo algumas possibilidades de _refactor_ e alguma alternativa temporária para poder testar o quanto antes.

**Comment by feljrz** [comment]
Estou trabalhando com os mesmos dados e provavelmente você já tenha enfrentado a dúvida que possuo. Os dados de empresa e sócios não possuem informações a respeito da ordem e dígito verificador, quanto a isto notei que muitas empresas têm relação 1-1 com os estabelecimentos, onde é possível obter estas informações e construir o CNPJ com 14 dígitos, mas como você tem tratado as que não a possuem? Complica um pouco mais quando olho para os sócios que podem ser sócios da matriz ou filiais.

**Comment by cuducos** [comment]
@feljrz Isso é o que expliquei na parte de [Arquitetura](https://github.com/cuducos/minha-receita/blob/dev/CONTRIBUTING.md#arquitetura) documentada nessa _issue_. Fiquei com a impressão que ainda podem ter dados faltando — mas aí só reclamando via LAI mesmo. 

Quando terminar de rodar de cabo a rabo com o PR #92 vou poder confirmar se é o caso (dados faltando) ou se era apenas uma impressão…

**Comment by feljrz** [comment]
> 
Obrigado pela resposta, estamos praticamente na mesma hahaha.
Quando ao PR #92 eu comecei com esta abordagem utilizando um banco relacional como intermediário e depois exportando para um NoSQL, algumas coisas que notei que talvez posso adiantar, além da falta de relacionamento de empresas e/ou sócios com os estabelecimentos há cerca de 15000 sócios sem relação alguma com os outros dados, foi o que mais me intrigou. Gostaria de contribuir, mas sou completamente ignorante em Go, pretendo aprender este ano sem falta, estou utilizando a stack Python > Postgres > Mongo + Elasticsearch.

**Comment by cuducos** [comment]
Curiosidades para o aprendizado:

> com esta abordagem utilizando um banco relacional como intermediário e depois exportando para um NoSQL

Pq um banco relacional como intermediário?
E pq um NoSQL depois?
Pode me falar mais dessas escolhas?

Sobre os problemas, precisamos fazer um relatório e perguntar via LAI. Seria legal ter scripts que gerem todos os detalhes sobre:

* falta de relacionamento de empresas com qualquer estabelecimento
* falta de relacionamento de sócio com empresas

Aí puxamos esse papo com a Receita Federal.

**Comment by feljrz** [comment]
O relacional como intermediário foi para basicamente estabelecer uma relação com joins entre o cnpj_base para depois gerar um JSON a partir de uma flat table. O NoSQL e os bancos são pela velocidade nas querys e requsitos técnicos da empresa. Sim precisamos fazer um relatório, já mandei email quanto a isto para o pessoal da Receita Federal, mas não obtive resposta. Assim que possível posso gerá-lo, quem sabe dão mais atenção.

**Comment by cuducos** [comment]
> Sim precisamos fazer um relatório, já mandei email quanto a isto para o pessoal da Receita Federal, mas não obtive resposta.

Foi um pedido pela LAI, protocolado e tal? Ou foi um email mais informal?

Minha ideia é ser pela LAI, pois aí eles tem a obrigação de responder — e se não respondermos a gente pode escalar para a CGU. Mas temos que ser precisos, por isso o relatório. Se tu não puxar isso (pode usar esse repositório, e Python, numa pasta separada para os relatórios, se quiser), eu puxo assim que atualizar producão!

**Comment by feljrz** [comment]
> Foi um pedido pela LAI, protocolado e tal? Ou foi um email mais informal?
Foi um email informal mesmo contando o que encontrei.

Estava analisando os dados de 12/2021 e parece que corrigiram o problema da falta de qualquer tipo de relacionamento do cnpj_base de cerca de 15000 sócios com qualquer outra tabela. Voltei ao snapshot que fiz dos dados de 10/2021 inferi o número de ordem como 001 para gerar o CNPJ completo destes sócios, conferi alguns utilizando a sua própria API, para todos que verifiquei havia relação com empresas em situação "Inativa" ou "Baixada".

Quanto aos dados de empresas que não possuem relação com estabelecimentos encontrei 4390077 casos distintos, fiz o mesmo processo anterior e utilizei sua API para consultar se existiam antes desta alteração no formato dos dados, e sim existiam. Posso ter cometido algum erro durante a geração desta tabela de estabelecimentos que ocasionou isto, ou pode ser uma falha no dados mesmo. Um exemplo é o CNPJ 79994075/0001-95 em que a base existe nos dados de empresa, mas não na de estabelecimentos, se for possível verifica se consegue encontrar este caso nos seus dados de estabelecimento, por favor que ai saberei que a falha esta aqui. De toda forma gerei um CSV com estes dados, caso queira dar uma olhada está aqui: https://github.com/feljrz/cnpj-to-report

**Comment by cuducos** [comment]
> Foi um email informal mesmo contando o que encontrei.

Tudo bem. Vamos organizar e depois protocolamos um oficial : )

> Posso ter cometido algum erro durante a geração desta tabela de estabelecimentos que ocasionou isto

Comentei lá: https://github.com/feljrz/cnpj-to-report/issues/1 — meu ponto: precisamos gerar esses dados (relatório) a partir dos dados abertos e com código aberto para dar transparência ao processo, possibilitar auditorias formais e informais, etc.

Penso em, terminando essa _issue_ aqui, criar essa verificação de consistência dos dados aqui no projeto mesmo caso isso facilite. Podemos começar com um `contrib/report.ipynb, por exemplo. O que acha?

**Comment by feljrz** [comment]
Concordo com você quanto a transparência, para abrir parte do projeto preciso da aprovação aqui da empresa, consigo confirmar isso na próxima semana. Em relação a construir o um "contrib/report.ipynb" para a auditoria eu topo demais contribuir.

**Comment by cuducos** [comment]
>  Em relação a construir o um "contrib/report.ipynb" para a auditoria eu topo demais contribuir.

Quando quiser rascunhar algo e abrir PR, pode começar. Senão começo quando conseguir fechar essa issue aqui 💜

**Comment by cuducos** [comment]
**UPDATE** importante nessa _issue_.

O código está 90% pronto, mas ainda não consegui rodar ele com 100% dos dados. Vez ou outra o processo quebra com `send on closed channel` — o que parece sumir quando comento esse [_defer close_](https://github.com/cuducos/minha-receita/blob/e76423774791b3f84ac1ff8ebbfb1ad2d30acc65/transform/venues.go#L99-L103) e, por alguns testes menores, esse [outro _defer close](https://github.com/cuducos/minha-receita/blob/e76423774791b3f84ac1ff8ebbfb1ad2d30acc65/transform/update.go#L96). Isso está super lento de debugar pois cada ciclo de editar, rodar e estudar o erro leva horas e horas (para rodar). E o pior: eu estava mais dedicado pois estava de férias — agora não estou mais.

Ainda estou tentando aqui, mas algumas perguntas ficam pipocando:

* Quão sério pode ser o erro de design que causa esse `send on closed channel`? Li e reli o código e ele não faz sentido. Com isso não quero dizer que não tem erro, mas que não tenho ideia do quão sério ele pode ser.
* Será que vale a pena mudar de estratégia? Por exemplo, usar a modelagem de dados da Receita Federal para evitar a etapa de enriquecimento (e acabar com mais tabelas no banco de dados), ou mesmo usar uma estrutura com um processo que envia mensagems para uma fila, uma fila (por exemplo, RabbitMQ), e processos que consomem essa fila?

**Comment by cuducos** [comment]
Os PRs #100 e #104 (obrigado @danielfireman) acho que completaram essa _issue_. Agora estou testando em um servidor com os dados completos, e se tudo der certo, atualizo o banco de dados de produção!
